services:

  # nginx
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  # php
  app:
    image: php:fpm-alpine3.17
    volumes:
      - ./app:/app